# Generated by Django 5.1.2 on 2024-11-04 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_limit', models.IntegerField(default=100)),
                ('duration_days', models.IntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='Trial', max_length=20)),
                ('plan_status', models.CharField(default='active', max_length=20)),
                ('emails_sent', models.IntegerField(default=0)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('system_info', models.JSONField(blank=True, null=True)),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
