# Generated by Django 5.1.2 on 2024-11-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_userprofile_plan_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='email_limit',
            field=models.IntegerField(default=10),
        ),
    ]
