# Generated by Django 5.1.2 on 2024-11-07 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_userprofile_current_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='device_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan_name',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Premium', 'Premium')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan_status',
            field=models.CharField(default='inactive', max_length=20),
        ),
    ]
