# Generated by Django 5.1.2 on 2024-11-08 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_plan_device_limit_alter_userprofile_current_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 8, 19, 16, 20, 677889, tzinfo=datetime.timezone.utc)),
        ),
    ]
