# Generated by Django 5.1.2 on 2024-11-09 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_userprofile_plan_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 20, 31, 22, 908972, tzinfo=datetime.timezone.utc)),
        ),
    ]
