# Generated by Django 5.1.2 on 2024-11-11 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 22, 11, 29, 818592, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
