# Generated by Django 5.1.2 on 2024-11-12 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_userprofile_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 19, 27, 19, 273144, tzinfo=datetime.timezone.utc)),
        ),
    ]
