# Generated by Django 5.1.2 on 2024-11-12 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_userprofile_plan_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 19, 29, 36, 625900, tzinfo=datetime.timezone.utc)),
        ),
    ]
