# Generated by Django 5.1.2 on 2024-11-13 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_remove_userprofile_refresh_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='system_info',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 22, 23, 32, 643551, tzinfo=datetime.timezone.utc)),
        ),
    ]
