# Generated by Django 5.1.2 on 2024-11-20 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_remove_userprofile_system_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 19, 43, 58, 276740, tzinfo=datetime.timezone.utc)),
        ),
    ]
