# Generated by Django 5.1.2 on 2025-01-04 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0023_alter_userprofile_plan_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 0, 0, 52, 444259, tzinfo=datetime.timezone.utc)),
        ),
    ]
