# Generated by Django 5.1.2 on 2025-01-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0041_alter_userprofile_plan_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan_name',
            field=models.CharField(blank=True, choices=[('Basic', 'basic'), ('Standard', 'standard'), ('Premium', 'premium'), ('Elite', 'elite')], max_length=20, null=True),
        ),
    ]
