# Generated by Django 5.1.2 on 2025-01-22 23:42

import subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0042_alter_userprofile_plan_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_plan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan_expiration_date',
            field=models.DateTimeField(blank=True, default=subscriptions.models.get_trial_expiration_date, null=True),
        ),
    ]
