# Generated by Django 5.1.2 on 2025-01-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0043_userprofile_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phonepe_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
