# Generated by Django 5.1.2 on 2025-01-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0044_userprofile_phonepe_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='email_limit',
            field=models.IntegerField(default=20),
        ),
    ]
