# Generated by Django 5.1.2 on 2025-01-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0045_alter_plan_email_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan_name',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium'), ('Elite', 'Elite')], max_length=20, null=True),
        ),
    ]
