# Generated by Django 5.1 on 2024-08-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Enter the HTML content of the email template.', verbose_name='Email Body'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(help_text='Enter a unique name for the template.', max_length=100, unique=True, verbose_name='Template Name'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(help_text='Enter the subject line for the email.', max_length=255, verbose_name='Email Subject'),
        ),
    ]
