# Generated by Django 5.1 on 2024-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0005_alter_emailtemplate_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='name',
            new_name='template_name',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('original', 'Original'), ('edited', 'Edited')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
