# Generated by Django 5.1 on 2024-08-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0006_rename_name_emailtemplate_template_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='template_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='template_type',
        ),
        migrations.RemoveField(
            model_name='usereditedtemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usereditedtemplate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='usereditedtemplate',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
