# Generated by Django 5.1 on 2024-08-22 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0007_rename_template_name_emailtemplate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereditedtemplate',
            name='original_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_sender.emailtemplate'),
        ),
    ]
