# Generated by Django 5.1 on 2024-09-04 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0008_alter_usereditedtemplate_original_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smtpserver',
            name='use_ssl',
        ),
    ]
