# Generated by Django 5.1 on 2024-09-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0010_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereditedtemplate',
            name='original_template',
        ),
        migrations.RemoveField(
            model_name='usereditedtemplate',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.DeleteModel(
            name='UserEditedTemplate',
        ),
    ]
