# Generated by Django 5.1 on 2024-10-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0011_remove_usereditedtemplate_original_template_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sender',
        ),
    ]
