# Generated by Django 5.1 on 2024-10-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0013_smtpserver_use_ssl_alter_smtpserver_use_tls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpserver',
            name='use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smtpserver',
            name='use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
