# Generated by Django 5.1 on 2024-10-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0014_alter_smtpserver_use_ssl_alter_smtpserver_use_tls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smtpserver',
            name='use_ssl',
        ),
    ]
