# Generated by Django 5.1 on 2024-10-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0015_remove_smtpserver_use_ssl'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='template_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
