# Generated by Django 5.1 on 2024-10-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0016_uploadedfile_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='template_name',
        ),
    ]
