# Generated by Django 5.1.2 on 2024-10-23 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0018_plan_emailstatuslog_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='max_emails',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='validity_days',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='plan_start_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='plan_status',
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='plan',
            name='email_limit',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_sender.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_count',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
