# Generated by Django 5.1.2 on 2024-10-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0021_userprofile_plan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan_status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
