# Generated by Django 5.1.2 on 2024-10-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0022_alter_userprofile_email_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='plan_expiry_date',
            new_name='plan_expiration_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_plan',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_count',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emails_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trial_plan_active',
            field=models.BooleanField(default=True),
        ),
    ]
