# Generated by Django 5.1.2 on 2024-10-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0028_userrefreshtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRefreshToken',
        ),
    ]
