# Generated by Django 5.1.2 on 2024-11-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0029_delete_userrefreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
