# Generated by Django 5.1.2 on 2024-11-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0030_userprofile_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='system_info',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_sender.plan'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan_name',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='Trial', max_length=20),
        ),
    ]
