# Generated by Django 5.1.2 on 2024-11-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0032_userprofile_refresh_token_userprofile_system_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_plan',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
