# Generated by Django 5.1.2 on 2024-12-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0018_emailstatuslog'),
        ('email_sender', '0033_remove_userprofile_current_plan_and_more'),
    ]

    operations = [
    ]
