# Generated by Django 5.1.2 on 2025-01-05 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0034_merge_20241205_0446'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-defined name for the contact file', max_length=255)),
                ('file', models.FileField(blank=True, help_text='Uploaded contact file', null=True, upload_to='contact_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='Data of the CSV row')),
                ('contact_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='email_sender.contactfile')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campaign name', max_length=255)),
                ('subject', models.CharField(help_text='Subject of the campaign', max_length=255)),
                ('delay_seconds', models.PositiveIntegerField(help_text='Delay between emails in seconds')),
                ('uploaded_file_key', models.CharField(blank=True, help_text='Key for the uploaded file', max_length=255, null=True)),
                ('display_name', models.CharField(blank=True, help_text='Display name for the sender', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the campaign was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the campaign was last updated')),
                ('smtp_servers', models.ManyToManyField(help_text='SMTP servers used for the campaign', related_name='campaigns', to='email_sender.smtpserver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('contact_list', models.ForeignKey(help_text='Contact list associated with the campaign', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='email_sender.contactfile')),
            ],
        ),
    ]
