# Generated by Django 5.1.2 on 2025-01-05 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0035_contactfile_contact_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='contact_list',
            new_name='email_list',
        ),
    ]
