# Generated by Django 5.1.2 on 2025-01-05 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0036_rename_contact_list_campaign_email_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='email_list',
            new_name='contact_list',
        ),
    ]
