# Generated by Django 5.1.2 on 2025-01-24 21:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0038_alter_emailstatuslog_from_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsubscribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsubscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_sender.contact')),
                ('contact_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_sender.contactfile')),
            ],
        ),
    ]
