# Generated by Django 5.1.2 on 2025-01-27 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0039_unsubscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsubscribed',
            name='email',
            field=models.EmailField(blank=True, help_text='Email of the unsubscribed contact', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='unsubscribed',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribes', to='email_sender.contact'),
        ),
        migrations.AlterField(
            model_name='unsubscribed',
            name='contact_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribes', to='email_sender.contactfile'),
        ),
        migrations.AlterField(
            model_name='unsubscribed',
            name='unsubscribed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
