# Generated by Django 5.1.2 on 2025-01-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0040_unsubscribed_email_alter_unsubscribed_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsubscribed',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='unsubscribed',
            name='contact_file',
        ),
        migrations.AddField(
            model_name='unsubscribed',
            name='contact_file_name',
            field=models.CharField(blank=True, help_text='Name of the contact file', max_length=255, null=True),
        ),
    ]
